### ISSUE TITLE
Implement operation of finishing task

### ISSUE THREAD

**Issue by itimofeev** [itimofeev/task2trip#3]
Task that in `in_progress` status can be finished or canceled.

- [x] add method(s) to API
- [x] change status in db
- [x] test

**Comment by itimofeev** [comment]
1) заказчик выбирает предложение /tast/{taskId}/offer/{offerId}
2) оффер помечается как выбранный + задача -> in_progress
3) добавить поле в offer.choosen_time в базе и в swagger Offer

**Comment by itimofeev** [comment]
in_progress -> finished 
in_progress -> canceled
Добавить метод в swagger:
```
PATCH /tast/{taskId}/offer/{offerId}
{
   "status": "finished"
}

```

**Comment by dananita** [comment]
сделано
