### ISSUE TITLE
Add place field to task

### ISSUE THREAD

**Issue by itimofeev** [itimofeev/task2trip#4]
Task must be assigned to some places

- [x] add table country(id string, key string, default_value string)
- [x] add table place (id, country_id, key string, default_value string)
- [x] add parameter place_id to task
- [x] create script that will create countries and places from xls file [Список стран и мест.xlsx](https://github.com/itimofeev/task2trip/files/2753661/default.xlsx)
- [x] add method to API for searching places

**Comment by dananita** [comment]
забыл добавить инфу о тестировании метода)

**Comment by dananita** [comment]
сделано
